---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fdk-prod-harvest-archive-pv
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  gcePersistentDisk:
    pdName: fdk-harvest-archive
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fdk-harvest-archive
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: ""
  volumeName: fdk-prod-harvest-archive-pv
