---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fdk-harvest-archive-deployment.yaml
  - fdk-harvest-archive-service.yaml
images:
  - name: fdk-harvest-archive
    newName: ghcr.io/informasjonsforvaltning/fdk-harvest-archive
    newTag: $(GIT_COMMIT_SHA)
